<?php

/**
 * @file
 * Contains fucs_form.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function fucs_studio_apartments_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the oneapp_home module.
    case 'help.page.fucs_studio_apartments':
      $output = '';
      $output .= '<h3>' . $this->t('About') . '</h3>';
      $output .= '<p>' . $this->t('Contains features for all fucs studio apartments') . '</p>';
      return $output;

    default:
  }
}

function fucs_studio_apartments_theme($existing, $type, $theme, $path) {
  return array(
    'fucs_studio_apartments' => [
      'variables' => [
        'form' => NULL,
      ],
      'template' => 'block--fucs-studio-apartments',
    ],
  );
}

/**
 * Implements hook_mail().
 */
function fucs_studio_apartments_mail($key, &$message, $params) {
  switch ($key) {
    case 'notificacion':
      $message['subject'] = $params['subject'];
      $message['body'][] = $params['message'];
      break;
  }
}
